### Get all the messages
GET http://localhost:8080/message/message

### Get the message by its id OK
GET http://localhost:8080/message/message/1

### Get the message by its id KO
GET http://localhost:8080/message/message/ko

### Post "Hello! ok"
POST http://localhost:8080/message/message
Content-Type: application/json

{
"id":"1",
"text":"Hello!"
}

### Post "Hello! ok ok "
POST http://localhost:8080/message/message
Content-Type: application/json

{
"id": "1",
"text": "Hello!"
}
### Post empty not body
POST http://localhost:8080/message/message
Content-Type: application/json

### Post ivalide JSON 1
POST http://localhost:8080/message/message
Content-Type: application/json

{}

### Post bad data
POST http://localhost:8080/message/message
Content-Type: application/json

{
"id": "1"
}
### Delete message by its id ok
DELETE http://localhost:8080/message/message/1

### Delete message by its id ok
DELETE http://localhost:8080/message/message/1

### Delete message by its id ko
DELETE http://localhost:8080/message/message/ko

### Update message ok
PUT http://localhost:8080/message/message/1
Content-Type: application/json

{
"id" : "2",
"text": "Salut!"
}
### Update message no body
PUT http://localhost:8080/message/message/2
Content-Type: application/json

### Update message empty body
PUT http://localhost:8080/message/message/2
Content-Type: application/json

{
}
### Update message empty wrong body
PUT http://localhost:8080/message/message/2
Content-Type: application/json

{
"id": 1